import COR16Compatible
import Mathlib.Analysis.LocallyConvex.WithSeminorms

noncomputable section

namespace Grad.CompatibleCompletion

open Grad.ClosedJets Grad.CartesianState Grad.FourierGrade Grad.COR12Extension Grad.COR13Completion

/-- Exactly the original Cartesian M2 seminorm at each grade, now as a
family on the untagged smooth core. There is no single all-grade norm. -/
def originalSeminormFamily (parameters : PhaseParameters) (dimension : ℕ) :
    SeminormFamily ℂ (ACore parameters dimension) ℕ :=
  fun grade => (cartesianGradeSeminorm parameters).comp (GradeCore.ofCoreLinear (grade := grade))

theorem originalSeminormFamily_apply {dimension : ℕ} (parameters : PhaseParameters)
    (grade : ℕ) (field : ACore parameters dimension) :
    originalSeminormFamily parameters dimension grade field =
      cartesianGradeSeminorm parameters (GradeCore.ofCoreLinear (grade := grade) field) := rfl

/-- The topology generated by the actual original seminorm family, named
explicitly rather than installing a Banach norm on the smooth core. -/
abbrev originalGradedTopology (parameters : PhaseParameters) (dimension : ℕ) :
    TopologicalSpace (ACore parameters dimension) :=
  (originalSeminormFamily parameters dimension).moduleFilterBasis.topology

theorem originalGradedTopology_withSeminorms (parameters : PhaseParameters) (dimension : ℕ) :
    WithSeminorms (topology := originalGradedTopology parameters dimension)
      (originalSeminormFamily parameters dimension) := by
  let _ := originalGradedTopology parameters dimension
  exact ⟨rfl⟩

theorem continuous_coreToCompatible {dimension : ℕ} (parameters : PhaseParameters) :
    @Continuous (ACore parameters dimension) (CompatibleAGrades parameters dimension)
      (originalGradedTopology parameters dimension) inferInstance (coreToCompatible parameters) := by
  let _ := originalGradedTopology parameters dimension
  have sourceSeminorms := originalGradedTopology_withSeminorms parameters dimension
  let _ := sourceSeminorms.topologicalAddGroup
  apply Continuous.subtype_mk
  apply continuous_pi
  intro grade
  let component : ACore parameters dimension →ₗ[ℂ] AGrade parameters dimension grade :=
    (aGradeEta parameters).toLinearMap.comp GradeCore.ofCoreLinear
  change Continuous component
  apply (norm_withSeminorms ℂ (AGrade parameters dimension grade)).continuous_of_continuous_comp
  intro index
  have normEquality : (normSeminorm ℂ (AGrade parameters dimension grade)).comp component =
      originalSeminormFamily parameters dimension grade := by
    ext field
    exact aGradeEta_norm_eq_cartesianGradeSeminorm parameters _
  rw [normEquality]
  exact sourceSeminorms.continuous_seminorm grade

theorem continuous_compatibleToCore {dimension : ℕ} (parameters : PhaseParameters) :
    @Continuous (CompatibleAGrades parameters dimension) (ACore parameters dimension)
      inferInstance (originalGradedTopology parameters dimension) (compatibleToCore parameters) := by
  let _ := originalGradedTopology parameters dimension
  have targetSeminorms := originalGradedTopology_withSeminorms parameters dimension
  apply targetSeminorms.continuous_of_continuous_comp
  intro grade
  have normEquality : (originalSeminormFamily parameters dimension grade).comp
      (compatibleToCore parameters) =
      (normSeminorm ℂ (AGrade parameters dimension grade)).comp
        (compatibleCoordinate parameters grade).toLinearMap := by
    ext family
    change cartesianGradeSeminorm parameters (GradeCore.ofCoreLinear (grade := grade)
      (compatibleToCore parameters family)) = ‖family.1 grade‖
    rw [← aGradeEta_norm_eq_cartesianGradeSeminorm, compatibleToCore_component]
  rw [normEquality]
  exact (compatibleCoordinate parameters grade).continuous.norm

/-- The algebraic compatible-limit equivalence is a homeomorphism from the
original seminorm-family topology to the inherited dependent-product topology. -/
def coreCompatibleHomeomorph {dimension : ℕ} (parameters : PhaseParameters) :
    @Homeomorph (ACore parameters dimension) (CompatibleAGrades parameters dimension)
      (originalGradedTopology parameters dimension) inferInstance := by
  let _ := originalGradedTopology parameters dimension
  exact {
    toEquiv := (coreCompatibleEquiv parameters).toEquiv
    continuous_toFun := continuous_coreToCompatible parameters
    continuous_invFun := continuous_compatibleToCore parameters }

theorem coreCompatibleHomeomorph_apply {dimension : ℕ} (parameters : PhaseParameters)
    (field : ACore parameters dimension) :
    coreCompatibleHomeomorph parameters field = coreCompatibleEquiv parameters field := rfl

/-- In particular the topology agrees with the initial topology of the
actual completed-component map, not just an abstract homeomorphic topology. -/
theorem originalGradedTopology_eq_induced {dimension : ℕ} (parameters : PhaseParameters) :
    originalGradedTopology parameters dimension =
      TopologicalSpace.induced (coreToCompatible (dimension := dimension) parameters)
        inferInstance := by
  let _ := originalGradedTopology parameters dimension
  exact (coreCompatibleHomeomorph (dimension := dimension) parameters).isInducing.eq_induced

end Grad.CompatibleCompletion
