import ASG9PhysicalSmoothSourceCore

noncomputable section

set_option maxHeartbeats 800000

open Set Filter MeasureTheory
open scoped Topology ContDiff Interval BigOperators ENNReal

namespace Grad.AnnularSourceGraph

open Grad.ClosedJets Grad.CartesianState Grad.SourceCollarDivision Grad.SourceBoundaryTrace
open Grad.GaugeCoefficients.Physical.WeightedTrace Grad.BoundaryKernelAction Grad.PhaseAlgebra

/-- Undo exactly the original endpoint phase and polynomial normalization. -/
def annularEndpointCoefficient (parameters : PhaseParameters) (dimension : ℕ)
    (radius : ℝ) (angular cell : ℕ) (field : AnnularEndpointTrace parameters dimension radius angular cell)
    (mode : ℤ × ℤ) : ComplexEuclidean dimension :=
  (annularConjugatingWeight parameters angular cell mode radius)⁻¹ • field mode

theorem annularEndpointCoefficient_normalization (parameters : PhaseParameters) (dimension : ℕ)
    (radius : ℝ) (angular cell : ℕ) (field : AnnularEndpointTrace parameters dimension radius angular cell)
    (mode : ℤ × ℤ) :
    annularConjugatingWeight parameters angular cell mode radius •
      annularEndpointCoefficient parameters dimension radius angular cell field mode = field mode := by
  rw [annularEndpointCoefficient, smul_smul,
    mul_inv_cancel₀ (annularConjugatingWeight_pos parameters angular cell mode radius).ne', one_smul]

theorem annularConjugatingWeight_sq (parameters : PhaseParameters) (angular cell : ℕ)
    (mode : ℤ × ℤ) (radius : ℝ) :
    annularConjugatingWeight parameters angular cell mode radius ^ 2 =
      Real.exp (2 * radialPhase parameters radius mode.2) *
        (1 + |(mode.1 : ℝ)|) ^ (2 * angular) * (1 + |(mode.2 : ℝ)|) ^ (2 * cell) := by
  unfold annularConjugatingWeight splitTangentialWeight
  rw [mul_pow, mul_pow, ← pow_mul, ← pow_mul]
  rw [Nat.mul_comm angular 2, Nat.mul_comm cell 2]
  rw [show 2 * radialPhase parameters radius mode.2 =
      radialPhase parameters radius mode.2 + radialPhase parameters radius mode.2 by ring,
    Real.exp_add]
  ring

/-- The inherited endpoint norm is exactly the physical H_e^(j,s) norm. -/
theorem annularEndpointTrace_norm_sq (parameters : PhaseParameters) (dimension : ℕ)
    (radius : ℝ) (angular cell : ℕ) (field : AnnularEndpointTrace parameters dimension radius angular cell) :
    ‖field‖ ^ 2 = ∑' mode : ℤ × ℤ,
      (Real.exp (2 * radialPhase parameters radius mode.2) *
        (1 + |(mode.1 : ℝ)|) ^ (2 * angular) * (1 + |(mode.2 : ℝ)|) ^ (2 * cell)) *
      ‖annularEndpointCoefficient parameters dimension radius angular cell field mode‖ ^ 2 := by
  have formula := lp.norm_rpow_eq_tsum (p := 2) (by norm_num) field
  norm_num at formula
  rw [formula]
  apply tsum_congr
  intro mode
  conv_lhs => rw [← annularEndpointCoefficient_normalization parameters dimension radius angular cell field mode]
  rw [norm_smul, Real.norm_of_nonneg (annularConjugatingWeight_pos parameters angular cell mode radius).le,
    mul_pow, annularConjugatingWeight_sq]

/-- AH11 evaluates the same physical smooth source at a or1; the exponential
at that endpoint is exactly the one generated by the conjugated graph. -/
theorem annularSourceTrace_physical_core (parameters : PhaseParameters) (dimension : ℕ) (lower : ℝ)
    (positive : 0 < lower) (bounded : lower < 1) (angular cell : ℕ) (endpoint : Fin 2)
    (core : (ℤ × ℤ) →₀ SmoothRadialCore dimension) (mode : ℤ × ℤ) :
    annularEndpointCoefficient parameters dimension (radialEndpointRadius lower endpoint) angular cell
      (annularSourceTrace parameters dimension lower positive bounded angular cell endpoint
        (physicalSourceCore parameters dimension lower angular cell core)) mode =
      (core mode).val.val.1 (radialEndpointRadius lower endpoint) := by
  unfold annularEndpointCoefficient
  rw [annularSourceTrace_apply, physicalSourceCore_apply, weightedRadialTrace_core]
  change (annularConjugatingWeight parameters angular cell mode (radialEndpointRadius lower endpoint))⁻¹ •
    (annularConjugatingWeight parameters angular cell mode (radialEndpointRadius lower endpoint) •
      (core mode).val.val.1 (radialEndpointRadius lower endpoint)) = _
  rw [smul_smul,
    inv_mul_cancel₀ (annularConjugatingWeight_pos parameters angular cell mode (radialEndpointRadius lower endpoint)).ne', one_smul]

/-- Uniqueness on the physical C∞ Fourier core, for either endpoint. -/
theorem annularSourceTrace_unique (parameters : PhaseParameters) (dimension : ℕ) (lower : ℝ)
    (positive : 0 < lower) (bounded : lower < 1) (angular cell : ℕ) (endpoint : Fin 2)
    (trace : AnnularSourceH1 parameters dimension lower angular cell →L[ℝ]
      AnnularEndpointTrace parameters dimension (radialEndpointRadius lower endpoint) angular cell)
    (coreLaw : ∀ core, trace (physicalSourceCore parameters dimension lower angular cell core) =
      annularSourceTrace parameters dimension lower positive bounded angular cell endpoint
        (physicalSourceCore parameters dimension lower angular cell core)) :
    trace = annularSourceTrace parameters dimension lower positive bounded angular cell endpoint := by
  apply ContinuousLinearMap.ext
  intro field
  apply isClosed_property (physicalSourceCore_denseRange parameters dimension lower angular cell)
    (isClosed_eq trace.continuous
      (annularSourceTrace parameters dimension lower positive bounded angular cell endpoint).continuous) _ field
  exact coreLaw

end Grad.AnnularSourceGraph
