import SBT10PhysicalRotation
import GC20H1Trace

noncomputable section
open Set Filter MeasureTheory
open scoped Topology ContDiff Interval BigOperators ENNReal
namespace Grad.SourceBoundaryTrace
open Grad.ClosedJets Grad.SourceCollarDivision
open Grad.GaugeCoefficients.Physical.WeightedTrace

/-- The accepted radial storage convention, as a linear map on genuine
continuous curves. The square-root factor represents the original r dr. -/
def weightedCurveLinear (dimension : ℕ) (lower : ℝ) :
    C(ℝ, ComplexEuclidean dimension) →ₗ[ℝ] RadialL2 dimension lower where
  toFun curve := radialToLp lower curve curve.continuous
  map_add' first second := by
    apply Lp.ext
    filter_upwards [radialToLp_ae lower (first + second) (first + second).continuous,
      radialToLp_ae lower first first.continuous, radialToLp_ae lower second second.continuous,
      Lp.coeFn_add (radialToLp lower first first.continuous) (radialToLp lower second second.continuous)]
      with radius total firstLaw secondLaw additive
    rw [total, additive, Pi.add_apply, firstLaw, secondLaw]
    exact smul_add _ _ _
  map_smul' scalar curve := by
    change radialToLp lower (scalar • curve) (scalar • curve).continuous =
      scalar • radialToLp lower curve curve.continuous
    apply Lp.ext
    filter_upwards [radialToLp_ae lower (scalar • curve) (scalar • curve).continuous,
      radialToLp_ae lower curve curve.continuous,
      Lp.coeFn_smul scalar (radialToLp lower curve curve.continuous)]
      with radius total curveLaw scaled
    rw [total, scaled, Pi.smul_apply, curveLaw]
    exact smul_comm (Real.sqrt radius) scalar (curve radius)

abbrev RadialEndpointAmbient (dimension : ℕ) (lower : ℝ) :=
  (RadialL2 dimension lower × RadialL2 dimension lower) × ComplexEuclidean dimension

/-- Both L2 coordinates and the endpoint come from the same genuine C1
curve. In particular the endpoint is not an independent boundary datum. -/
def weightedEndpointCore (dimension : ℕ) (lower : ℝ) :
    collarSmoothGraph (ComplexEuclidean dimension) →ₗ[ℝ] RadialEndpointAmbient dimension lower :=
  { toFun := fun core => ((weightedCurveLinear dimension lower core.val.1,
      weightedCurveLinear dimension lower core.val.2), core.val.1 1)
    map_add' := by
      intro first second
      change ((weightedCurveLinear dimension lower (first.val.1 + second.val.1),
        weightedCurveLinear dimension lower (first.val.2 + second.val.2)), _) = _
      rw [map_add, map_add]
      rfl
    map_smul' := by
      intro scalar core
      change ((weightedCurveLinear dimension lower (scalar • core.val.1),
        weightedCurveLinear dimension lower (scalar • core.val.2)), _) = _
      rw [map_smul, map_smul]
      rfl }

/-- The closed trace relation for the literal weighted radial derivative
graph. It is generated by actual C1 functions, not arbitrary L2 values. -/
def radialEndpointGraph (dimension : ℕ) (lower : ℝ) :
    Submodule ℝ (RadialEndpointAmbient dimension lower) :=
  (LinearMap.range (weightedEndpointCore dimension lower)).topologicalClosure

theorem radialEndpointGraph_core (dimension : ℕ) (lower : ℝ)
    (core : collarSmoothGraph (ComplexEuclidean dimension)) :
    weightedEndpointCore dimension lower core ∈ radialEndpointGraph dimension lower :=
  Submodule.le_topologicalClosure _ ⟨core, rfl⟩

theorem weightedCurve_energy_lower (dimension : ℕ) (lower : ℝ) (positive : 0 < lower)
    (bounded : lower ≤ 1) (curve : C(ℝ, ComplexEuclidean dimension)) :
    lower * (∫ radius in lower..1, ‖curve radius‖ ^ 2) ≤
      ‖weightedCurveLinear dimension lower curve‖ ^ 2 := by
  change _ ≤ ‖radialToLp lower curve curve.continuous‖ ^ 2
  rw [radialToLp_norm_sq lower positive.le bounded, ← intervalIntegral.integral_const_mul]
  apply intervalIntegral.integral_mono_on bounded
    ((continuous_const.mul (curve.continuous.norm.pow 2)).intervalIntegrable lower 1)
    ((continuous_id.mul (curve.continuous.norm.pow 2)).intervalIntegrable lower 1)
  intro radius inside
  exact mul_le_mul_of_nonneg_right inside.1 (sq_nonneg _)

theorem weightedEndpointCore_bound (dimension : ℕ) (lower : ℝ)
    (positive : 0 < lower) (bounded : lower < 1)
    (core : collarSmoothGraph (ComplexEuclidean dimension)) :
    lower * ‖(weightedEndpointCore dimension lower core).2‖ ^ 2 ≤
      collarTraceConstant lower * (‖(weightedEndpointCore dimension lower core).1.1‖ ^ 2 +
        ‖(weightedEndpointCore dimension lower core).1.2‖ ^ 2) := by
  have trace := scalar_collar_trace core.val.1 core.val.2 lower 1 bounded le_rfl
    core.val.1.continuous core.val.2.continuous (fun radius _ => core.property radius)
  simp only [one_mul, inv_one] at trace
  have value := weightedCurve_energy_lower dimension lower positive bounded.le core.val.1
  have slope := weightedCurve_energy_lower dimension lower positive bounded.le core.val.2
  have constant : 0 ≤ collarTraceConstant lower := zero_le_one.trans (collarTraceConstant_one_le bounded)
  change lower * ‖core.val.1 1‖ ^ 2 ≤ _
  calc
    _ ≤ lower * (collarTraceConstant lower *
        ((∫ radius in lower..1, ‖core.val.1 radius‖ ^ 2) +
          (∫ radius in lower..1, ‖core.val.2 radius‖ ^ 2))) :=
      mul_le_mul_of_nonneg_left trace positive.le
    _ = collarTraceConstant lower *
        (lower * (∫ radius in lower..1, ‖core.val.1 radius‖ ^ 2) +
          lower * (∫ radius in lower..1, ‖core.val.2 radius‖ ^ 2)) := by ring
    _ ≤ _ := mul_le_mul_of_nonneg_left (add_le_add value slope) constant

/-- The trace estimate survives completion in the original weighted
derivative graph, with a uniform constant on the fixed half collar. -/
theorem radialEndpointGraph_bound (dimension : ℕ) (lower : ℝ)
    (positive : 0 < lower) (bounded : lower < 1)
    (point : RadialEndpointAmbient dimension lower)
    (member : point ∈ radialEndpointGraph dimension lower) :
    lower * ‖point.2‖ ^ 2 ≤ collarTraceConstant lower *
      (‖point.1.1‖ ^ 2 + ‖point.1.2‖ ^ 2) := by
  have closed : IsClosed {point : RadialEndpointAmbient dimension lower |
      lower * ‖point.2‖ ^ 2 ≤ collarTraceConstant lower *
        (‖point.1.1‖ ^ 2 + ‖point.1.2‖ ^ 2)} := by
    exact isClosed_le (continuous_const.mul (continuous_snd.norm.pow 2))
      (continuous_const.mul (((continuous_fst.fst).norm.pow 2).add
        ((continuous_fst.snd).norm.pow 2)))
  apply closure_minimal (s := (LinearMap.range (weightedEndpointCore dimension lower) : Set _))
    (fun point member => ?_) closed member
  rcases member with ⟨core, rfl⟩
  exact weightedEndpointCore_bound dimension lower positive bounded core

theorem radialEndpointGraph_unique (dimension : ℕ) (lower : ℝ)
    (positive : 0 < lower) (bounded : lower < 1)
    (value slope : RadialL2 dimension lower) (first second : ComplexEuclidean dimension)
    (firstLaw : ((value, slope), first) ∈ radialEndpointGraph dimension lower)
    (secondLaw : ((value, slope), second) ∈ radialEndpointGraph dimension lower) : first = second := by
  have bound := radialEndpointGraph_bound dimension lower positive bounded _
    ((radialEndpointGraph dimension lower).sub_mem firstLaw secondLaw)
  change lower * ‖first - second‖ ^ 2 ≤ collarTraceConstant lower *
    (‖value - value‖ ^ 2 + ‖slope - slope‖ ^ 2) at bound
  simp only [sub_self, norm_zero, zero_pow (by decide : 2 ≠ 0), zero_add, mul_zero] at bound
  have zeroNorm : ‖first - second‖ ^ 2 ≤ 0 := by nlinarith
  exact sub_eq_zero.mp (norm_eq_zero.mp (by nlinarith [norm_nonneg (first - second)]))

end Grad.SourceBoundaryTrace
